jobs:
  include:
    - stage: test
      dist: trusty
      language: go
      go: 1.8
      env:
      - KUBERNETES_VERSION=v1.7.0
      script:
      - set -e
      - curl -Lo helm.tar.gz https://storage.googleapis.com/kubernetes-helm/helm-v2.6.1-linux-amd64.tar.gz && tar xvf helm.tar.gz && sudo mv linux-amd64/helm /usr/local/bin
      - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBERNETES_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.21.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      # Install nsenter
      - docker build -t ubuntu-nsenter ./hack/ubuntu-nsenter
      - docker run -v /usr/local/bin:/hostbin ubuntu-nsenter cp /nsenter /hostbin/nsenter
      # Create a cluster. We do this as root as we are using the 'docker' driver.
      # We enable RBAC on the cluster too, to test the RBAC in Navigators chart
      - sudo -E CHANGE_MINIKUBE_NONE_USER=true minikube start --vm-driver=none --kubernetes-version="$KUBERNETES_VERSION" --extra-config=apiserver.Authorization.Mode=RBAC
      - while true; do if kubectl get nodes; then break; fi; echo "Waiting 5s for kubernetes to be ready..."; sleep 5; done
      # Fix problems with kube-dns + rbac
      - kubectl create serviceaccount --namespace kube-system kube-dns
      - make BUILD_TAG=latest build e2e-test

    - stage: test
      dist: trusty
      language: go
      go: 1.8
      script:
      - make verify

    - stage: build
      dist: trusty
      services:
      - docker
      language: go
      go: 1.8
      script:
      - make go_build docker_build
      - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
          mkdir -p ~/.docker && echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json && chmod 600 ~/.docker/config.json;
          make docker_push IMAGE_TAGS="${TRAVIS_COMMIT} latest";
        fi
