# dist: trusty

# env:
# - KUBERNETES_VERSION=v1.7.0
# - KUBERNETES_VERSION=v1.6.4
# - KUBERNETES_VERSION=v1.5.3

# services:
# - docker

# language: go

# go: 1.8

# script:
# - set -e
# - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBERNETES_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
# - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.21.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
# - sudo -E CHANGE_MINIKUBE_NONE_USER=true minikube start --vm-driver=none --kubernetes-version="$KUBERNETES_VERSION"
# - make BUILD_TAG=latest e2e-test

jobs:
  allow_failures:
    - env: KUBERNETES_VERSION=v1.5.3

  include:

    - stage: test
      dist: trusty
      language: go
      go: 1.8
      script:
      - make verify

    - stage: build
      dist: trusty
      services:
      - docker
      language: go
      go: 1.8
      script:
      - make go_build docker_build
      - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
          mkdir -p ~/.docker && echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json && chmod 600 ~/.docker/config.json;
          make docker_push IMAGE_TAGS="${TRAVIS_COMMIT} latest";
        fi
