apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-controller
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
      component: controller
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: controller
    spec:
{{- if .Values.controller.serviceAccount }}
      serviceAccountName: {{ .Values.controller.serviceAccount }}
      serviceAccount: {{ .Values.controller.serviceAccount }}
{{- else }}
      serviceAccountName: {{ template "fullname" . }}-controller
      serviceAccount: {{ template "fullname" . }}-controller
{{- end }}
      containers:
        - name: controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          args:
          - navigator-controller
{{- if .Values.controller.namespace }}
          - --namespace={{ .Values.controller.namespace }}
{{- end }}
{{- if .Values.featureGates }}
          - --feature-gates={{ .Values.featureGates }}
{{- end }}
          - --leader-election-namespace={{ .Release.Namespace }}
          - --v={{ .Values.controller.logLevel }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
